apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.bluemix.net/rewrite-path: "serviceName=acmeair-flight-service rewrite=/"
  name: acmeair-flight-ingress
spec:
  rules:
  - host: INGRESS_URL
    http:
      paths:
      - path: /flight
        backend:
          serviceName: acmeair-flight-service
          servicePort: 9080
