{{ if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{  .Chart.Name }}-ingress"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.rewriteTarget }}
    nginx.ingress.kubernetes.io/ssl-redirect: "{{ .Values.ingress.sslRedirect }}"
    nginx.ingress.kubernetes.io/connection-proxy-header: "keep-alive"
    ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.rewriteTarget }}
    ingress.kubernetes.io/ssl-redirect: "{{ .Values.ingress.sslRedirect }}"
    ingress.kubernetes.io/connection-proxy-header: "keep-alive"

spec:
  rules:
  - host:
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
          serviceName: "{{ .Values.service.name }}"
          servicePort: {{ .Values.service.servicePort }}
{{ end }}
